[package]
name = "timekeeper"
description = "Proof of History (PoH)"
authors = ["Rivane Rasetiansyah <re@nvll.me>"]
repository = "https://github.com/rvnrstnsyh/timekeeper"
version = "0.0.1"
edition = "2024"
rust-version = "1.86.0"

[dependencies]
crossterm = "0.29.0"
hex = "0.4.3"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
