name: Check

on:
  push:
    branches:
      - main
      - dev*
      - feat*
  pull_request:
    branches:
      - main
      - dev*
      - feat*

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy -- -A clippy::needless_return -A clippy::too_many_arguments -D warnings

      - name: Tests
        run: cargo test --all
